#
# Each instruction in this file generates a new layer that gets pushed to your local image cache
#
 
#
# Lines preceeded by # are regarded as comments and ignored
#
 
#
# The line below states we will base our new image on the Latest Official Ubuntu 
FROM compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-rel-3.0:6
 
#
# Identify the maintainer of an image
LABEL maintainer="rahulgoud.mula@amd.com"
 
#
# Update the image to the latest packages
RUN echo 'app    ALL=(ALL:ALL) ALL' >> /etc/sudoers
#RUN useradd -ms /bin/bash app
RUN adduser app --gecos --disabled-password
RUN echo "app:app" | chpasswd
RUN usermod app -aG video

RUN sudo apt install chrpath && sudo apt install rccl
#
# Pull rccl & rccl-tests from github.
RUN cd /home/app/ && git clone https://github.com/ROCmSoftwarePlatform/rccl && git clone https://github.com/ROCmSoftwarePlatform/rccl-tests.git

RUN mkdir -p /home/app/rccl/build 

#RUN cd /home/app/rccl/build/ && CXX=/opt/rocm/bin/hcc cmake .. && make package && sudo dpkg -i *.deb
RUN chmod 755 /home/app/rccl-tests/* 
#RUN cd /home/app/rccl-tests/ && make; exit 0

#
# Expose port 80
#EXPOSE 80
 
#
# Last is the actual command to start up NGINX within our Container
#CMD ["nginx", "-g", "daemon off;"]
